---
title: "Angewandte Statistik Bachelor of Science"
subtitle: "Workshop Deskriptive Statistik"
author:
  - name: Patric Eichelberger
    email: patric.eichelberger@bfh.ch
    affiliations:
      - name: Bern University of Applied Sciences
        department: School of Health Professions
        group: Physiotherapy Research, Bern Movement Lab
---

## Aufgabe 1 {.smaller}

M&Ms Stichproben

Fülle die Befragung M&Ms Stichproben auf Moodle aus. Benutze die Daten aus der M&Ms Datenerhebung (siehe Moodle) und jamovi um den Mittelwert und die Standardabweichung deiner Stichprobe zu berechnen.

## Aufgabe 2 {.smaller}

Wir haben folgende Angaben:

| ID  | Gewicht | Handspanne |
|-----|---------|------------|
| P01 | 70.0    | 20.0       |
| P02 | 66.8    | 14.0       |
| P03 | 59.5    | 15.0       |
| P04 | 58.0    | 21.5       |
| P05 | 64.0    | 20.0       |

- Handelt es sich um eine Population oder eine Stichprobe? Begründe!
- Wo in der Tabelle befinden sich die Beobachtungseinheiten?
- Wo in der Tabelle befinden sich die Merkmale?
- Wo in der Tabelle befinden sich die Merkmalsausprägungen?

## Aufgabe 3 {.smaller}

Ordne den Merkmalen die richtigen Skalenniveaus zu.

| Merkmal          | qualitativ-nominal | qualitativ-ordinal | quantitativ-diskret | quantitativ-kontinuierlich |
|------------------|:------------------:|:------------------:|:-------------------:|:--------------------------:|
| Fusslänge        |                    |                    |                     |                            |
| Schuhgrösse      |                    |                    |                     |                            |
| Temperatur in °C |                    |                    |                     |                            |
| Nationalität     |                    |                    |                     |                            |
| Alter            |                    |                    |                     |                            |
| Kaffees pro Tag  |                    |                    |                     |                            |

## Aufgabe 4 {.smaller}

Wir benutzen für diese Übung die gemessenen M&Ms Gewichtswerte. Der Datensatz dazu befindet sich in Moodle.

- Importiere die Daten in jamovi.
- Wie gross ist der Stichprobenumfang?
- Welcher Wert liegt auf der 25\%-Perzentile? Welcher auf der 75\%-Perzentile?
- Wie gross ist der Interquartilsabstand?
- Wie viele Werte liegen innerhalb des Interquartilsabstands?
- Wie viele Werte liegen über der 90\%-Perzentile? (Tipp: Erstelle einen Filter)
- Zeichne einen Boxplot für das M\&Ms Gewicht von Hand.
- Erstelle mit jamovi ein Histogramm für das M\&Ms Gewicht und interpretiere. Was stellst du fest im Vergleich mit dem Boxplot (Stichwort Symmetrie)?
- Untersuche den Einfluss der Farbe auf das M\&Ms Gewicht.

## Aufgabe 5

Häufigkeitstabellen

Wir benutzen für diese Übung die gemessenen M&Ms Gewichtswerte. Der Datensatz dazu befindet sich in Moodle.

Erstelle eine Tabelle mit den absoluten und relativen Häufigkeiten der M&Ms Farben.
